FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .
ENV HOST=0.0.0.0 PORT=3000 CHOKIDAR_USEPOLLING=true CI=true
EXPOSE 3000
CMD ["npm","start"]